title: Welcome to my website!
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "Varun Babbar"
  email: "varundbabbar@gmail.com"
  url: "VarunBabbar.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Varun Babbar"
year : "2022"
